org.gradle.jvmargs=-Xmx3G -Xms512m -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
minecraft_version=1.20.1
minecraft_version_range=[1.20.1]
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[40,)
java_version=17
mod_version=0.2.10
mod_id=my_mod
mod_name=锟斤拷烫烫烫
mod_license=MIT
mod_authors=ModMind
mod_description=一把伤害超高的剑——锟斤拷
maven_group=dev.modmind.my_mod
archives_base_name=kunjinkao_forge_1.20.1
